{
 "title": "miral-test",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Query Stats",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select \nquantile(0.5)(query_duration_ms) p50, \nquantile(0.9)(query_duration_ms) p90,\nquantile(0.99)(query_duration_ms) p99,\nmax(query_duration_ms) max,\navg(query_duration_ms) avg,\nstddevPop(query_duration_ms) stddev\nfrom clusterAllReplicas(c1, system, query_log)\nwhere\nquery_kind = 'Select'\nand http_user_agent not like 'ClickHouse-Jdbc%'\nand type = 'QueryFinish'\nand not empty(arrayFilter(\n                  (x) -> x LIKE 'data.%',\n                  tables)\n              )\nand $__timeFilter(event_time);"
    }
   ]
  },
  {
   "title": "Selects / Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select toStartOfMinute(event_time), count()\nfrom clusterAllReplicas(c1, system, query_log)\nwhere\nquery_kind = 'Select'\nand http_user_agent not like 'ClickHouse-Jdbc%'\nand type = 'QueryFinish'\nand not empty(arrayFilter(\n                  (x) -> x LIKE 'data.%',\n                  tables)\n              )\nand $__timeFilter(event_time)\ngroup by 1"
    }
   ]
  },
  {
   "title": "Rows Inserted / Minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "with q as (SELECT toStartOfMinute(event_time) sec,\n                  sum(rows)\n           FROM clusterAllReplicas(c1, system.part_log)\n           WHERE (event_type = 'NewPart')\n             AND $__timeFilter(event_time)\n             GROUP BY sec\n           ORDER BY sec ASC)\n\nselect * from q"
    }
   ]
  },
  {
   "title": "Select Latency (Log Scale)",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "select event_time, query_duration_ms as duration\nfrom clusterAllReplicas(c1, system, query_log)\nwhere \nquery_kind = 'Select'\nand http_user_agent not like 'ClickHouse-Jdbc%'\nand type = 'QueryFinish'\nand not empty(arrayFilter(\n                  (x) -> x LIKE 'data.%',\n                  tables)\n              )\nand $__timeFilter(event_time)\norder by event_time desc\nlimit 1000\n"
    }
   ]
  },
  {
   "title": "Top Queries",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT\n    event_time,\n    query_id,\n    arrayFilter(\n        (x) -> x LIKE 'data.%',\n        tables) as tables,\n    query_duration_ms as duration,\n  memory_usage as memory\nFROM\n    clusterAllReplicas(c1, system.query_log)\nWHERE\n    $__timeFilter(event_time)\n    AND query_kind = 'Select'\n    AND type = 'QueryFinish'\n   and user != 'monitoring-internal'\n    and http_user_agent not like 'ClickHouse-Jdbc%'\n    and not empty(tables)\nORDER BY\n    memory DESC;"
    }
   ]
  }
 ]
}